### ISSUE TITLE
VeSync Bridge Polling Interval Description

### ISSUE THREAD

**Issue by martynjsimpson** [dag81/vesyncOpenhabPyPort#1]
The polling interval "help text" makes reference to Hue in the Bridge configuration page.

"Seconds between fetching values from the Hue bridge. Default is 60."

![image](https://user-images.githubusercontent.com/49991502/151538257-0c1e6a28-2964-4dee-a0f1-6ffb6a30b826.png)

**Comment by dag81** [comment]
Good catch - thank you - I'll patch it up later - when my son finishes playing Minecraft :)

**Comment by dag81** [comment]
Corrections merged in against: Commit: 9507d812bf150892723499782aa330bb54e97ccd [9507d81]

Currently in main. 

The field mentioned should be removed its redundant, and I've updated the naming on the other field to include humidifiers as it covers both filters & humidifiers (as they both report effectively slow changing data).
