### ISSUE TITLE
Device LUH-D301S-WEU not supported

### ISSUE THREAD

**Issue by nougad** [dag81/vesyncOpenhabPyPort#4]
I'm using the manual build for Openhab 3.2.0 with device LUH-D301S-WEU.

Configuring the bridge results in `Device Model or Type not supported by this thing` because the device is not in the supported list:

https://github.com/dag81/vesyncOpenhabPyPort/blob/65670e16a2a96a6f15b7c40bc74bfada98073c5b/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncDeviceAirHumidifierHandler.java#L117-L123

https://github.com/dag81/vesyncOpenhabPyPort/blob/65670e16a2a96a6f15b7c40bc74bfada98073c5b/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncDeviceAirHumidifierHandler.java#L61-L62

Is that on purpose?

**Comment by dag81** [comment]
Hi @nougad,

It's should be in the builds for 3.3 looking at the branch submitted for OpenHabs repo, but I have not yet had time to rebuild the older 3.2 jar. I'll see if I can out how to build against 3.2 again later on.

This is a humidifier correct? I'll ping you once it's done - if you could confirm any mapping issues that would be great thanks - as I don't think anyone has tried that model yet.

**Comment by dag81** [comment]
Good catch thanks - looks like I didn't merge that change over. Will do, and advise when the builds are updated.

**Comment by dag81** [comment]
@nougad[ Please try this one ](https://github.com/dag81/vesyncOpenhabPyPort/blob/main/manual%20builds/org.openhab.binding.vesync-3.2.0-SNAPSHOT.jar). Thanks for spotting that.

**Comment by nougad** [comment]
Thank you for the fast help! It works without any problems so far. I copied the text configuration from your README and found two small things:

* The readme mentions `vesync:AirHumidifier:vesyncServers:loungeHumidifier:mistVirtualLevel` but it should be `mistLevel` (without `Virtual`).
* The device does not support the Night Light but OpenHab still discovers it as channel. It's already checked here:

https://github.com/dag81/vesyncOpenhabPyPort/blob/main/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncDeviceAirHumidifierHandler.java#L214-L217

but not here

https://github.com/dag81/vesyncOpenhabPyPort/blob/main/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncDeviceAirHumidifierHandler.java#L75-L77

I will do more tests tomorrow but looks like everything is working just fine.

**Comment by dag81** [comment]
Thanks for checking @nougad. It's good to pick these up before the PR for OpenHab addon's gets reviewed :) The night light should be removed now thank you 👍. If you could check that night lights gone that would be great thanks. On windows I've had to delete userdata/cache, but Linux/MacOS seems to be fine, detecting the replacement file. (I haven't had time to figure out what it's really doing there). (Basically as versioning isn't in these build's, but as I'm hoping soon to get it in the official repo's 🤞 that won't be a issue). Thanks for the doc's pointer I'll update those now - I think most people so far have auto-discovered.

**Comment by nougad** [comment]
Yes I can confirm the night light is not discovered anymore with the last build :+1:

Looking forward to see it in the official repo :smiley:

**Comment by dag81** [comment]
@nougad Many thanks :) I'll close this issue now. Looking at the backlog of reviews I'm guessing it may take a while - but catching these bits now should certainly help thanks 👍
