### ISSUE TITLE
LUH-A602S-WEU not supported

### ISSUE THREAD

**Issue by morrisb74** [dag81/vesyncOpenhabPyPort#5]
Guessing that it is the same as LUH-A602S-WUS, but the european version :)

**Comment by dag81** [comment]
HI @morrisb74, I'll try to take a look at the weekend as I need to spin back up the dev environment systems. Unfortunately work is hectic at the moment, along with other bits but I'll try to do a build by next Monday with that code in.

**Comment by dag81** [comment]
@morrisb74 are you running 3.3? I was about to upload a build that should that ID for you - if you could validate please?

**Comment by dag81** [comment]
@morrisb74 please confirm this [build ](https://github.com/dag81/vesyncOpenhabPyPort/blob/feature/LUH-602S-WEU/manual%20builds/LUH-602S-WEU/org.openhab.binding.vesync-3.3.0-SNAPSHOT.jar) works as expected when you can. It's built against 3.3 let me know if you need a build against 3.2 instead please? Thanks in advance

**Comment by morrisb74** [comment]
> @morrisb74 please confirm this [build ](https://github.com/dag81/vesyncOpenhabPyPort/blob/feature/LUH-602S-WEU/manual%20builds/LUH-602S-WEU/org.openhab.binding.vesync-3.3.0-SNAPSHOT.jar) works as expected when you can. It's built against 3.3 let me know if you need a build against 3.2 instead please? Thanks in advance

Your release works, I used the 3.3.0 Snapshot, But I'm guessing not everyone wants to "Bleeding Edge" software :-D
It automagically found it after adding (and configuring) the bridge... But don't understand why you want to mask the username :-) ...

**Comment by dag81** [comment]
@morrisb74 Many thanks I'll merge that to main then. The "Bleeding Edge" bit - that was built against the PR I have for trying to get it into the official repo - so confirmed and validated code. It's only snapshot as thats currently how I know to build it against the different revisions. I think the masking is there simply as it's PII if open on the screen (struggling to remember). User's can always unmask from memory if req. (Maybe they will request thats changed when they review the PR).

**Comment by dag81** [comment]
@morrisb74 yeap they reacted to the password field for the username as well :) That context has been removed for the PR into the main repo. Thanks for testing - have a great weekend.
